from pathlib import Path
p=Path('src/js/07-reading-voice-bootstrap.part.js')
s=p.read_text()
old="""function syncVoiceUi(){const enabled=!!appState.readingAssistEnabled&&!!appState.readingAssistReady&&!appState.editor,listening=enabled&&!!appState.voiceListening,speaking=enabled&&!!appState.voiceSpeaking,starting=enabled&&!!voiceMicStarting&&!listening&&!speaking,state=listening?'listening':speaking?'speaking':starting?'starting':'idle';document.body.classList.toggle('reading-assist-enabled',enabled);document.body.classList.toggle('voice-speaking',speaking);document.body.classList.toggle('voice-listening',listening);document.body.classList.toggle('voice-mic-starting',starting);const b=el('voiceFloatBtn');if(b){b.hidden=!enabled;b.dataset.voiceState=state;b.textContent=listening?'🎙️':speaking?'🔊':starting?'🎙️':'🗣️';b.setAttribute('aria-pressed',listening||starting?'true':'false');b.setAttribute('aria-label',listening?'Ouvindo. Toque para cancelar':speaking?'Lendo em voz alta':starting?'Abrindo microfone':'Leitura por voz pronta. Toque para falar');b.title=b.getAttribute('aria-label');}const t=el('settingsReadingAssist');if(t)t.checked=!!appState.readingAssistEnabled;applyMusicVolume(1);}"""
new="""function syncVoiceUi(){const enabled=!!appState.readingAssistEnabled&&!!appState.readingAssistReady&&!appState.editor,listening=enabled&&!!appState.voiceListening,speaking=enabled&&!!appState.voiceSpeaking,starting=enabled&&!!voiceMicStarting&&!listening&&!speaking,state=listening?'listening':speaking?'speaking':starting?'starting':'idle';document.body.classList.toggle('reading-assist-enabled',enabled);document.body.classList.toggle('voice-speaking',speaking);document.body.classList.toggle('voice-listening',listening);document.body.classList.toggle('voice-mic-starting',starting);const b=el('voiceFloatBtn');if(b){b.hidden=!enabled;b.dataset.voiceState=state;b.textContent=listening?'🎙️':speaking?'🔊':starting?'⏳':'🗣️';b.setAttribute('aria-pressed',listening?'true':'false');b.setAttribute('aria-label',listening?'Ouvindo agora. Fale sua opção':speaking?'Lendo em voz alta':starting?'Preparando o microfone. Aguarde o ícone de microfone':'Leitura por voz pronta. Toque para falar');b.title=b.getAttribute('aria-label');}const t=el('settingsReadingAssist');if(t)t.checked=!!appState.readingAssistEnabled;applyMusicVolume(1);}"""
if old not in s: raise SystemExit('syncVoiceUi target not found')
s=s.replace(old,new,1)
old="""try{rec.lang='pt-BR';rec.continuous=false;rec.interimResults=false;rec.maxAlternatives=1;}catch{}
    let handled=false;
    rec.onstart=()=>{if(token!==voiceListenToken||appState.voiceRecognition!==rec)return;voiceMicStarting=false;appState.voiceListening=true;syncVoiceUi();};
    rec.onresult=e=>{handled=true;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();const transcript=e.results?.[0]?.[0]?.transcript?.trim?.()||'';if(answerSurface)handleVoiceAnswerTranscript(transcript,answerSurface);else handleVoiceTranscript(transcript,actions);};
    rec.onnomatch=()=>{handled=true;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();handleVoiceTranscript('',actions);};
    rec.onerror=e=>{handled=true;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();const code=String(e?.error||'');if(/not-allowed|service-not-allowed/.test(code)){readingMicPermissionDenied=true;toast('Permita o uso do microfone para responder por voz.');return;}if(!/aborted/.test(code))setTimeout(()=>{if(appState.readingAssistEnabled&&token===voiceListenToken)startVoiceListening(actions,contextKey,answerSurface);},300);};
    rec.onend=()=>{if(appState.voiceRecognition===rec)appState.voiceRecognition=null;const wasListening=!!appState.voiceListening;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();if(!handled&&wasListening&&appState.readingAssistEnabled&&token===voiceListenToken)setTimeout(()=>startVoiceListening(actions,contextKey,answerSurface),260);};
    setTimeout(()=>{if(!appState.readingAssistEnabled||token!==voiceListenToken||contextKey!==appState.voiceContextKey||appState.voiceRecognition!==rec){voiceMicStarting=false;syncVoiceUi();try{rec.abort();}catch{}return;}try{rec.start();}catch{voiceMicStarting=false;appState.voiceListening=false;if(appState.voiceRecognition===rec)appState.voiceRecognition=null;syncVoiceUi();toast('O microfone ficou indisponível.');}},120);"""
new="""try{rec.lang='pt-BR';rec.continuous=false;rec.interimResults=false;rec.maxAlternatives=5;}catch{}
    let handled=false,audioStarted=false,startFallback=null;
    const recognitionIsCurrent=()=>token===voiceListenToken&&appState.voiceRecognition===rec&&contextKey===appState.voiceContextKey;
    const markAudioCaptureStarted=()=>{if(!recognitionIsCurrent())return;audioStarted=true;if(startFallback){clearTimeout(startFallback);startFallback=null;}voiceMicStarting=false;appState.voiceListening=true;syncVoiceUi();};
    rec.onstart=()=>{if(!recognitionIsCurrent())return;startFallback=setTimeout(()=>{if(recognitionIsCurrent()&&!audioStarted)markAudioCaptureStarted();},300);};
    rec.onaudiostart=markAudioCaptureStarted;
    rec.onresult=e=>{if(!recognitionIsCurrent())return;handled=true;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();const result=e.results?.[e.resultIndex??0]||e.results?.[0],alternatives=result?[...result]:[],transcripts=alternatives.map(a=>String(a?.transcript||'').trim()).filter(Boolean);let transcript=transcripts[0]||'';if(!answerSurface&&transcripts.length>1&&actions.length){let bestScore=-1;for(const candidate of transcripts){const score=rankedVoiceActions(candidate,actions)[0]?.score||0;if(score>bestScore){bestScore=score;transcript=candidate;}}}if(answerSurface)handleVoiceAnswerTranscript(transcript,answerSurface);else handleVoiceTranscript(transcript,actions);};
    rec.onnomatch=()=>{if(!recognitionIsCurrent())return;handled=true;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();handleVoiceTranscript('',actions);};
    rec.onerror=e=>{if(!recognitionIsCurrent()&&String(e?.error||'')!=='aborted')return;handled=true;if(startFallback){clearTimeout(startFallback);startFallback=null;}voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();const code=String(e?.error||'');if(/not-allowed|service-not-allowed/.test(code)){readingMicPermissionDenied=true;toast('Permita o uso do microfone para responder por voz.');return;}if(!/aborted/.test(code))setTimeout(()=>{if(appState.readingAssistEnabled&&token===voiceListenToken)startVoiceListening(actions,contextKey,answerSurface);},300);};
    rec.onend=()=>{if(startFallback){clearTimeout(startFallback);startFallback=null;}if(appState.voiceRecognition===rec)appState.voiceRecognition=null;const wasListening=!!appState.voiceListening;voiceMicStarting=false;appState.voiceListening=false;syncVoiceUi();if(!handled&&wasListening&&appState.readingAssistEnabled&&token===voiceListenToken)setTimeout(()=>startVoiceListening(actions,contextKey,answerSurface),260);};
    setTimeout(()=>{if(!appState.readingAssistEnabled||token!==voiceListenToken||contextKey!==appState.voiceContextKey||appState.voiceRecognition!==rec){voiceMicStarting=false;syncVoiceUi();try{rec.abort();}catch{}return;}try{rec.start();}catch{voiceMicStarting=false;appState.voiceListening=false;if(appState.voiceRecognition===rec)appState.voiceRecognition=null;syncVoiceUi();toast('O microfone ficou indisponível.');}},220);"""
if old not in s: raise SystemExit('recognition target not found')
s=s.replace(old,new,1)
p.write_text(s)
