from pathlib import Path

p = Path('src/js/07-reading-voice-bootstrap.part.js')
s = p.read_text()
old = """  async function runVoiceNarrativeChoice(index){const section=appState.book?.sections?.[appState.sectionId],choice=section?.choices?.[index];if(!choice)throw new Error(`Alternativa ${index+1} não existe na seção atual.`);if(bookModeEnabled()&&!appState.editor&&bookPaginationActive()&&appState.bookSubpageCount>1&&appState.bookSubpageIndex<appState.bookSubpageCount-1){renderBookSubpage(appState.bookSubpageCount-1,{commit:true,hint:false});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));}return choose(choice,index);}"""
new = """  async function runVoiceNarrativeChoice(index){const sectionId=appState.sectionId,section=appState.book?.sections?.[sectionId],choice=section?.choices?.[index];if(!choice)throw new Error(`Alternativa ${index+1} não existe na seção atual.`);if(bookModeEnabled()&&!appState.editor&&bookPaginationActive()&&appState.bookSubpageCount>1&&appState.bookSubpageIndex<appState.bookSubpageCount-1){renderBookSubpage(appState.bookSubpageCount-1,{commit:true,hint:false});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));}const findButton=()=>[...document.querySelectorAll('#choices button[data-choice-index]')].find(btn=>Number(btn.dataset.choiceIndex)===index&&!btn.disabled);let button=findButton();if(!button){renderChoices();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));button=findButton();}if(!button)throw new Error(`Botão da alternativa ${index+1} não está disponível.`);button.click();await new Promise(resolve=>setTimeout(resolve,180));return true;}"""
if s.count(old) != 1:
    raise SystemExit(f'runVoiceNarrativeChoice target count: {s.count(old)}')
s = s.replace(old, new)

old2 = """async function runResolvedVoiceAction(action){if(!action)return false;const before=appState.sectionId;cancelVoiceRecognition();let actionError=null;try{await action.run?.();}catch(err){actionError=err;console.warn('Ação por voz falhou.',err);}const advanced=appState.sectionId!==before;if(actionError&&!advanced){await voiceSpeak('A ação ficou indisponível.',{remember:false});if(appState.readingAssistEnabled){const surface=voiceCurrentSurface();if(surface?.actions?.length){appState.voiceContextKey=surface.key;await startVoiceListening(surface.actions,surface.key,surface.kind==='answer-input'?surface:null);}}return false;}appState.voiceContextKey='';appState.voiceLastNarratedPromptKey='';if(advanced)appState.voiceLastNarratedStoryKey='';scheduleVoiceCycle(true,420);return true;}"""
new2 = """async function runResolvedVoiceAction(action){if(!action)return false;const before=appState.sectionId;cancelVoiceRecognition();let actionError=null;try{await action.run?.();}catch(err){actionError=err;console.warn('Ação por voz falhou.',err);}const advanced=appState.sectionId!==before;if(actionError&&!advanced){if(action.type==='alternative'){appState.voiceContextKey='';scheduleVoiceCycle(true,260);return false;}await voiceSpeak('A ação ficou indisponível.',{remember:false});if(appState.readingAssistEnabled){const surface=voiceCurrentSurface();if(surface?.actions?.length){appState.voiceContextKey=surface.key;await startVoiceListening(surface.actions,surface.key,surface.kind==='answer-input'?surface:null);}}return false;}appState.voiceContextKey='';appState.voiceLastNarratedPromptKey='';if(advanced)appState.voiceLastNarratedStoryKey='';scheduleVoiceCycle(true,420);return true;}"""
if s.count(old2) != 1:
    raise SystemExit(f'runResolvedVoiceAction target count: {s.count(old2)}')
s = s.replace(old2, new2)
p.write_text(s)
